### ISSUE TITLE
npm build error: digital envelope routines::unsupported

### ISSUE THREAD

**Issue by thewtex** [OpenImaging/miqa#298]
```
  |     at Storage.finished (/opt/client/noe_modules/enhanced-resolve/lib/CachedInpu
tFileSystem.js:55:16)
npm_1       |     at /opt/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:
9
npm_1       | node:internal/crypto/hash:67                                                     
npm_1       |   this[kHandle] = new _Hash(algorithm, xofLen);
npm_1       |                   ^                                                              
npm_1       |                                  
npm_1       | Error: error:0308010C:digital envelope routines::unsupported
npm_1       |     at new Hash (node:internal/crypto/hash:67:19)
npm_1       |     at Object.createHash (node:crypto:135:10)                                    
npm_1       |     at module.exports (/opt/client/node_modules/webpack/lib/util/createHash.js:13
5:53)
npm_1       |     at NormalModule._initBuildHash (/opt/client/node_modules/webpack/lib/NormalMo
dule.js:417:16)
npm_1       |     at handleParseError (/opt/client/node_modules/webpack/lib/NormalModule.js:471
:10)
npm_1       |     at /opt/client/node_modules/webpack/lib/NormalModule.js:503:5
npm_1       |     at /opt/client/node_modules/webpack/lib/NormalModule.js:358:12
npm_1       |     at /opt/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
npm_1       |     at iterateNormalLoaders (/opt/client/node_modules/loader-runner/lib/LoaderRun
ner.js:214:10)
npm_1       |     at Array.<anonymous> (/opt/client/node_modules/loader-runner/lib/LoaderRunner
.js:205:4)
npm_1       |     at Storage.finished (/opt/client/node_modules/enhanced-resolve/lib/CachedInpu
tFileSystem.js:55:16)
npm_1       |     at /opt/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:
9
npm_1       |     at /opt/client/node_modules/graceful-fs/graceful-fs.js:123:16
npm_1       |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_fi
le_context:68:3) {
npm_1       |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization 
error' ],
npm_1       |   library: 'digital envelope routines',                                          
npm_1       |   reason: 'unsupported',                                                         
npm_1       |   code: 'ERR_OSSL_EVP_UNSUPPORTED'                                               
npm_1       | }                                
npm_1       |                                  
npm_1       | Node.js v17.4.0                  
npm_1       | npm notice                       
npm_1       | npm notice New minor version of npm available! 8.3.1 -> 8.4.0
npm_1       | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.4.0>
npm_1       | npm notice Run `npm install -g npm@8.4.0` to update!
npm_1       | npm notice                       
miqa_npm_1 exited with code 1  d
```

**Comment by thewtex** [comment]
We tried:

```
NODE_OPTIONS=--openssl-legacy-provider
```

in dev/.env.docker-compose.

did not work.

**Comment by dchiquito** [comment]
The problem was that node version >=17 deprecated some OpenSSL algorithms, some of which were still being used by one of our dependencies. The fix was to include an environment variable flag in the docker-compose configuration for the `npm` container that reenables the deprecated algorithms. Hopefully we can remove eventually when the dependencies are updated.
