### ISSUE TITLE
Tox InvocationError

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#57]
I am trying to run the test suite on miqa using tox. I've followed all the steps in the README.md and successfully start the django server (`./manage.py runserver`) and celery (`celery --app miqa.celery worker ...`).

I execute tox:

`$ tox`

It runs for a really, really long time (because it is looking at all the files in the venv created in step 3 of initia setup). Eventually it performs the following
```
check-migrations run-test-pre: PYTHONHASHSEED='1629803711'
check-migrations run-test: commands[0] | /home/miqa/.tox/check-migrations/bin/python
  ./manage.py makemigrations --check --dry-run
```

And throws an error:

```
Traceback (most recent call last):
  File "/home/miqa/./manage.py", line 20, in <module>
    main()
  File "/home/miqa/./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/configurations/importer.py", line 182, in load_module
    reraise(err, "Couldn't setup configuration '{0}'".format(cls_path))
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/configurations/importer.py", line 164, in load_module
    cls.setup()
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/configurations/base.py", line 127, in setup
    setup_value(cls, name, value)
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/configurations/values.py", line 15, in setup_value
    actual_value = value.setup(name)
  File "/home/miqa/.tox/check-migrations/lib/python3.9/site-packages/configurations/values.py", line 105, in setup
    raise ValueError('Value {0!r} is required to be set as the '
ValueError: Couldn't setup configuration 'miqa.settings.TestingConfiguration':  Value 'DATABASES' is required to be set as the environment variable 'DJANGO_DATABASE_URL' 
ERROR: InvocationError for command /home/miqa/.tox/check-migrations/bin/python ./manage.py makemigrations --check --dry-run (exited with code 1)
___________________________________ summary ____________________________________
  lint: commands succeeded
ERROR:   check-migrations: commands failed
```

The error appears to be that tox isn't finding the environment variables it needs to perform a test migration - but I have run `source ./dev/export-env.sh` as instructed (in both the django and celery sessions).

I cloned miqa again into a fresh folder and attempted to run tox without performing any of the "Develop Natively (advanced) instructions and this reduced the time tox ran drastically - it finished in under a minute, as opposed to perhaps ~15 mins. when run with the instructions (because it is scanning so much more code in the venv).

But, as expected, it fails with the same error shown earlier.

I tried running `source ./dev/export-env.sh` to see if that might help but it didn't.

Wondering if there is a simple step I'm missing?

Thanks!

**Comment by venkatabhishek** [comment]
Are you working in a virtual environment? I'm not sure if this would mess with anything but I just repeated the entire steps for native development as listed exactly in the **Initial Setup** section of the README, and it seemed to work fine

Can you see that the environment variables are there before you run tox? I.e. something simple as one of the variables in `./dev/.env.docker-compose-native` such as 
```echo $DJANGO_CONFIGURATION```

**Comment by davidshq** [comment]
Thanks! That led me down the right path. I had run `source /miqa/bin/activate` when opening both the django and celery terminal sessions but I hadn't run it again when I opened tox terminal session. Once I did it completed successfully.

I'll close this issue.
