### ISSUE TITLE
Has anyone successfully run MIQA on GitHub Codespaces?

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa#580]
Curious if anyone has successfully used GitHub Codespaces to run/develop MIQA?

I was able to spin up all of the Docker containers, access the site, and import simple-scans to MIQA. Once I tried loading the images, however, I get the message, "Error loading this frame".

Looking at the devtools console I can see:

Caught exception loading next frame

loadFileAndGetData caught error getting data

```
{message: 'Could not read file: /work/image.nii.gz', stack: 'Error: Could not read file: /work/image.nii.gz\n   …O.worker.js:33:7\n    at new Promise (<anonymous>)'}

message: "Could not read file: /work/image.nii.gz"

stack: 
"Error: Could not read file: /work/image.nii.gz\n    at readImageEmscriptenFSFile 
(http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:2219:11)\n    at _inputToResponse
 (http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:1323:69)\n    at _callee2$ (http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:1433:47)\n    at tryCatch 
(http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:128:40)\n    at Generator.invoke [as _invoke]
 (http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:358:22)\n    at Generator.next (http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:183:21)\n    at asyncGeneratorStep 
(http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:4:24)\n    at _next 
(http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:26:9)\n    at 
http://localhost:8081/itk/WebWorkers/ImageIO.worker.js:33:7\n    at new Promise (<anonymous>)"

[[Prototype]]: Object
```

Not planning to spend a ton of time on it, but was curious if anyone had seen something similar and had a quick fix.

**Comment by aashish24** [comment]
Not to my knowledge @davidshq
